### ISSUE TITLE
Error when adding empty 7z

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/Modnix#30]
[empty.zip](https://github.com/Sheep-y/Modnix/files/4733446/empty.zip)

System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Sheepy.Modnix.MainGUI.SevenZipArchiveReader.<>c.<ListFiles>b__4_1(String e)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Sheepy.Modnix.MainGUI.SevenZipArchiveReader.ListFiles()

**Comment by Sheep-y** [comment]
Fix in commit 70f4f4c1bd3ec8c1cebc8236e80f05ad9931956b and 0c001203dfd3b3f28b1f567c15e7c575a8973c41.

**Comment by Sheep-y** [comment]
Released in Modnix 2.5.2
